product.version=0.10.0-preview
product.versionCode=10
product.applicationId=com.airgesture.control
android.minSdk=26
android.targetSdk=36
android.compileSdk=36
android.gradlePlugin=8.10.1
baseline.apk.filename=AirGestureControl-v0.10.0-preview.apk
baseline.apk.sha256=7b161e73cd6ac397362c2ee65e3c62bcaa9a14587cc09fd871df7ec72f8ba015
