product.version=0.10.0-preview
product.versionCode=10
product.applicationId=com.airgesture.control
android.minSdk=26
android.targetSdk=37
android.compileSdk=37
android.gradlePlugin=9.4.0
gradle.version=9.8.0
kotlin.version=2.4.20
baseline.apk.filename=AirGestureControl-v0.10.0-preview.apk
baseline.apk.sha256=7b161e73cd6ac397362c2ee65e3c62bcaa9a14587cc09fd871df7ec72f8ba015
